name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
      - development

jobs:
  Build_and_publish:
    uses: nittin-cz/.github/.github/workflows/build_publish_dot_net_app.yml@main
    with:
      file_with_version: Directory.Build.props
      dot_net_version: 8
      csproj_path: src/Kentico.Xperience.Aira
      build_file: Kentico.Xperience.Aira.csproj
      package_name: Kentico.Xperience.Aira
    secrets:
      ci_token: ${{ secrets.NITTIN_CI_TOKEN }}